### ISSUE TITLE
Possible Bug: Not Syncing Website Icons from Passwords WebUI

### ISSUE THREAD

**Issue by Saijin-Naib** [hegocre/NextcloudPasswords#29]
In the Passwords NextCloud WebUI, a number of favicons have been fetched and applied, but they do not show in the app even with the setting enabled.

**Comment by hegocre** [comment]
Hi @Saijin-Naib 

I've pushed a commit that should greatly improve icon loading experience, since now I use a library that does it 1000 times better than I manually did.

I should note that app gets the icons using the Nextcloud server API, which means it is responsible for providing the correct ones. Changing this would mean having to connect to external websites, which would be against the app philosophy.

Feel free to try the new CI build and get back with some feedback:wink:

**Comment by Saijin-Naib** [comment]
It seems to fetch the favicons perfectly fine, matching the server icons exactly.

Only missing icons are the ones the server didn't fetch, so I'm happy!

Initial load on list of nearly 1000 passwords is a bit pokey, but my device isn't exactly connected perfectly anymore (MTK Helio P60, 6GB RAM)

**Comment by hegocre** [comment]
Yeah, it is possible that the first time it fetches the icons, it takes a while. I've also found that it also depends on the server speed, not just the device. The good part is that after the first time, the icons are cached, so it should work much better
