### ISSUE TITLE
Folders tab: search is not working inside folders

### ISSUE THREAD

**Issue by TtuxX** [hegocre/NextcloudPasswords#59]
### Checklist

- [X] I am able to reproduce the bug with the latest version [here](https://github.com/hegocre/NextcloudPasswords/releases/latest).
- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which report the same bug.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

1.0.6

### Steps to reproduce the bug

1. Open Passwords app
2. Do to Folders tab
3. Search for a password that is inside a folder
4. Search results is empty 

### Expected behavior

Search should crawl through folders

### Actual behavior

Search only returns the passwords that on the root folder, but not subfolders

**Comment by hegocre** [comment]
Hello!

The behavior you describe is actually expected, it is how I personally found it to be expected (I'm in a folder, I only search inside the folder). If I want to search all passwords, I go to the passwords tab.

Maybe it would be good to know what the majority of people expect to happen when they search while on the folders tab.

For instance, do we agree it should only search for favortie passwords on the favorites tab?

**Comment by g-work** [comment]
I think it depends what kind of passwords you are storing. In my usecase it would be useful to search everywhere (although I wouldn't expect it to) because I mainly store passwords for different services like onlineshops, (mail-)accounts and so on. Since they are quite unique, a simple search by first letters mostly gets me the wanted password. In fact I don't really need folders.

But I could imagine there are usecases where password's titles are very similar (e.g. servers that differ only in IP) so folders (and a search that does only search in a specified folder) are useful.

Perhaps you could make it an option?

**Comment by hegocre** [comment]
Hi @g-work, thank you for your input.

I agree that making it an option could be a solution. The problem I have with this approach is that, if we start making everything that could be expected to work in different ways an option, we may never end, as everyone can have different interpretations of different things.

I think both use cases you show are covered on the app: if you have different passwords and want to search on all passwords, you default to the all passwords app, so that it searches everywhere. Otherwise, if you usually work in folders, you start in the folders tab, and you search inside them.

Keep in mind that you can always change tabs before or while searching by just changing tabs, and the query is kept on the search bar, which allows you to switch from searching all passwords to folders and vice versa with just one tap.

Let me know if you think there is something more I should consider, or if you have any other suggestion.

Thank you again!

**Comment by TtuxX** [comment]
Hi there :)

What about a hybrid solution replicating the behavior of the Passwords application, where, when searching in a folder, it displays only the folder's results, but then, if nothing is found, it displays a centered global search proposal message:

**There is nothing here**
Nothing has been found for search: 'keywordnotfound'
_Attempt a global search for: 'keywordnotfound'_

Screenshot:

![screenshot](https://github.com/hegocre/NextcloudPasswords/assets/6570830/68cffb20-84ca-4529-bb6b-b6cb6f141292)

**Comment by hegocre** [comment]
Hey @TtuxX 

I really like the solution you are proposing, hadn't thought of it, and I think it is great.

Thank you, I will do this!
