### ISSUE TITLE
Feature Request: More PIN digits (like Android default)

### ISSUE THREAD

**Issue by acidicX** [hegocre/NextcloudPasswords#64]
### Checklist

- [X] I have checked and there are *no existing issues* - [open](https://github.com/hegocre/NextcloudPasswords/issues) or [closed](https://github.com/hegocre/NextcloudPasswords/issues?q=is%3Aissue+is%3Aclosed) - which request the same feature.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Android allows up to 17 digits as system lock, it would be nice if this app could align the PIN digits policy (min 4 / max 17).

### Why do you want this feature?

I tend to use more than 4 digits for PINs

**Comment by acidicX** [comment]
Also: is the E2E-Password encrypted (if saved) with the PIN? If not, I'd open another feature request ;)

Thanks for the app by the way, the autofill seems to work much better than the NC Passwords one.

**Comment by hegocre** [comment]
Hello, and thank you for your feedback.

I will add the variable PIN length to my list of features to implement.

And to answer your question, the saved master password is not encrypted with the PIN, since that would leave users without PIN protection in a more vulerable spot. Instead, it uses EncryptedSharedPreferences, a Shared Preferences instance that encrypts the preferences values, making it almost imposible for other apps appart from Nextcloud Passwords from reading the values, even on rooted devices. You can read more information about how it works [here](https://gauravkh-9648.medium.com/this-blog-will-help-you-understand-the-internals-encryptedsharedpreferences-961992c6e5a). 

Hope this answers your question! 😄

**Comment by acidicX** [comment]
@hegocre cool! That should be secure enough. Thank you! :)

**Comment by hegocre** [comment]
Hello

You can now use up to 17 digits on your PIN.

Best regards!
